import { useState } from 'react';
import type { FormEvent } from 'react';
import { ArrowRight, Check, ExternalLink, Link2, Save, ShieldCheck } from 'lucide-react';
import type { Contract, Dashboard, Vehicle } from '../shared/types.js';
import { useDirty } from './Experience.js';
import { addMonths } from '../shared/dates.js';
import { dateTime, errorMessage, getJSON, sendJSON } from './api.js';

export function Settings({ dashboard, reload }: { dashboard: Dashboard; reload: () => Promise<void> }) {
  const today = new Date().toISOString().slice(0, 10);
  const [contract, setContract] = useState<Contract>(dashboard.contract ?? { startDate: today, endDate: addMonths(today, 36), handoverKm: 0, totalKm: 45_000, timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone });
  const [annual, setAnnual] = useState(15_000); const [months, setMonths] = useState(36);
  const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [vehicles, setVehicles] = useState<Vehicle[]>([]);
  const act = async (action: () => Promise<void>) => { setBusy(true); setError(null); setMessage(null); try { await action(); await reload(); } catch (error) { setError(errorMessage(error)); } finally { setBusy(false); } };
  const save = (event: FormEvent) => { event.preventDefault(); void act(async () => { await sendJSON('/api/contract', 'PUT', contract); setMessage('Dein Leasingvertrag wurde gespeichert.'); }); };
  useDirty('contract', JSON.stringify(contract) !== JSON.stringify(dashboard.contract ?? { startDate: today, endDate: addMonths(today, 36), handoverKm: 0, totalKm: 45_000, timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone }));
  const tesla = dashboard.tesla;
  return <>
    {error && <div className="alert error" role="alert">{error}</div>}{message && <div className="alert success" role="status"><Check size={16}/>{message}</div>}
    <div className="settings-grid"><section className="card"><div className="section-heading"><div><div className="eyebrow">01 / LEASING</div><h2>Dein Kilometerbudget</h2></div></div><form className="contract-form" onSubmit={save}>
      <div className="form-row"><label>Vertragsbeginn<input type="date" required value={contract.startDate} onChange={event => setContract({ ...contract, startDate: event.target.value })}/></label><label>Rückgabedatum<input type="date" required min={contract.startDate} value={contract.endDate} onChange={event => setContract({ ...contract, endDate: event.target.value })}/></label></div>
      <small>Die Vertragslaufzeit endet zu Beginn des Rückgabetags.</small>
      <label>Kilometerstand bei Übergabe<input type="number" min={0} step="0.1" required value={contract.handoverKm} onChange={event => setContract({ ...contract, handoverKm: event.target.valueAsNumber })}/></label>
      <div className="input-helper"><strong>Kontingent aus Jahreskilometern berechnen</strong><div className="form-row"><label>km pro Jahr<input type="number" min={1} value={annual} onChange={event => setAnnual(event.target.valueAsNumber)}/></label><label>Laufzeit in Monaten<input type="number" min={1} max={120} value={months} onChange={event => setMonths(event.target.valueAsNumber)}/></label></div><button className="text-button" type="button" disabled={!Number.isFinite(annual) || annual <= 0 || !Number.isInteger(months) || months <= 0 || months > 120 || !contract.startDate} onClick={() => { try { setContract({ ...contract, totalKm: annual * months / 12, endDate: addMonths(contract.startDate, months) }); } catch (error) { setError(errorMessage(error)); } }}>Kontingent und Rückgabedatum übernehmen <ArrowRight size={14}/></button></div>
      <label>Verbindliche Vertragsgesamt-km<input type="number" min={1} max={2_000_000} step="0.1" required value={contract.totalKm} onChange={event => setContract({ ...contract, totalKm: event.target.valueAsNumber })}/><small>Bitte mit deinem Leasingvertrag abgleichen.</small></label>
      <label>Zeitzone<input required value={contract.timeZone} onChange={event => setContract({ ...contract, timeZone: event.target.value })} placeholder="Europe/Berlin"/><small>Für Tagesgrenzen und Fahrtzeiten.</small></label>
      <button className="button primary" disabled={busy}><Save size={16}/>Vertrag speichern</button>
    </form></section>
    <section className="card connection-card"><div className="section-heading"><div><div className="eyebrow">02 / FAHRZEUG</div><h2>Mit Tesla verbinden</h2></div><Link2 size={23}/></div><p>Jede Installation nutzt eine eigene Tesla Developer App. Hinterlege Client-ID, Secret, Domain und Zertifikate auf deinem Server gemäß der Einrichtungsanleitung.</p>
      <div className="setup-step"><span className="step-number">1</span><div><h3>Developer App registrieren</h3><p>Der öffentliche Schlüssel muss bereits unter deiner App-Domain erreichbar sein.</p><button className="button secondary" disabled={busy || dashboard.demo} onClick={() => void act(async () => { await sendJSON('/api/tesla/register', 'POST', {}); setMessage('Developer App bei Tesla registriert.'); })}>Domain registrieren</button></div></div>
      <div className="setup-step"><span className="step-number">2</span><div><h3>Tesla-Konto autorisieren</h3><p>Die Anmeldung erfolgt direkt bei Tesla.</p><button className="button secondary" disabled={busy || dashboard.demo} onClick={() => void act(async () => { const result = await sendJSON<{ url: string }>('/api/tesla/authorize', 'POST', {}); window.location.assign(result.url); })}>{tesla.connected ? 'Erneut verbinden' : 'Mit Tesla anmelden'}<ExternalLink size={14}/></button></div></div>
      <div className="setup-step"><span className="step-number">3</span><div><h3>Fahrzeug auswählen</h3><p>{tesla.vehicle ? `${tesla.vehicle.name} · ${tesla.vehicle.vin}` : 'Ein Model 3 oder Model Y mit aktueller Fahrzeugsoftware.'}</p><button className="button secondary" disabled={busy || !tesla.connected || dashboard.demo} onClick={() => void act(async () => { const result = await getJSON<{ vehicles: Vehicle[] }>('/api/tesla/vehicles'); setVehicles(result.vehicles); if (result.vehicles.length === 0) setMessage('Kein unterstütztes Model 3/Y im Tesla-Konto gefunden.'); })}>Fahrzeuge laden</button>{vehicles.map(vehicle => <button className="vehicle-choice" key={vehicle.vin} disabled={busy} onClick={() => void act(async () => { await sendJSON('/api/tesla/vehicle', 'PUT', { vin: vehicle.vin }); setVehicles([]); })}>{vehicle.name} · {vehicle.vin}<ArrowRight size={14}/></button>)}</div></div>
      <div className="setup-step"><span className="step-number">4</span><div><h3>Schlüssel koppeln & Erfassung starten</h3><p>Füge den virtuellen Schlüssel in der Tesla-App hinzu und prüfe anschließend die Voraussetzungen.</p><div className="button-row"><button className="button secondary" disabled={!tesla.vehicle || busy || dashboard.demo} onClick={() => void act(async () => { const result = await getJSON<{ url: string }>('/api/tesla/pairing'); window.location.assign(result.url); })}>Schlüssel hinzufügen</button><button className="button secondary" disabled={!tesla.vehicle || busy || dashboard.demo} onClick={() => void act(async () => { await sendJSON('/api/tesla/check', 'POST', {}); setMessage('Fahrzeugstatus aktualisiert.'); })}>Status prüfen</button></div><button className="button primary" disabled={!tesla.keyPaired || busy || dashboard.demo || Boolean(tesla.problem)} onClick={() => void act(async () => { await sendJSON('/api/tesla/configure', 'POST', {}); setMessage('Konfiguration gesendet. Bei nächster Verbindung übernimmt das Fahrzeug die Einstellungen.'); })}>Erfassung konfigurieren <ArrowRight size={15}/></button></div></div>
      <details className="diagnostics"><summary>Technische Verbindungsdetails</summary><dl className="connection-details"><div><dt>Autorisierung</dt><dd>{tesla.connected ? 'Verbunden' : 'Nicht verbunden'}</dd></div><div><dt>Fahrzeugsoftware</dt><dd>{tesla.firmware ?? '—'}</dd></div><div><dt>Fleet Telemetry</dt><dd>{tesla.telemetryVersion ?? '—'} · benötigt ≥ 1.3.0</dd></div><div><dt>Virtueller Schlüssel</dt><dd>{tesla.keyPaired ? 'Gekoppelt' : 'Nicht gekoppelt'}</dd></div><div><dt>Erfassung</dt><dd>{tesla.synced ? 'Synchronisiert' : tesla.configured ? 'Wartet auf Fahrzeug' : 'Nicht konfiguriert'}</dd></div><div><dt>Letzte Prüfung</dt><dd>{dateTime(tesla.checkedAt, contract.timeZone)}</dd></div></dl></details>
      {tesla.problem && <div className="alert warning">{tesla.problem}</div>}
      <div className="privacy-callout"><ShieldCheck size={20}/><p>Nur Gang und Kilometerstand. Keine Standorte, keine Live-Karte, keine automatischen Wakeups. Im Tesla-Portal Abrechnung und Ausgabenlimit prüfen; das monatliche Freikontingent ist keine unbegrenzte Gratisnutzung.</p></div>
      {tesla.connected && !dashboard.demo && <button className="text-button danger" disabled={busy} onClick={() => { if (window.confirm('Telemetrie-Erfassung beenden und die lokale Tesla-Verbindung trennen? Bisherige Daten bleiben erhalten.')) void act(async () => { await sendJSON('/api/tesla/disconnect', 'POST', {}); setMessage('Tesla-Verbindung getrennt.'); }); }}>Tesla-Verbindung trennen</button>}
    </section></div>
  </>;
}
